twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_name: 'KEMEAT'
        copyright: 'Copyright 2021 _ KEMEAT'
    form_themes: ['bootstrap_5_layout.html.twig']   

when@test:
    twig:
        strict_variables: true
